{{- if not .Values.jmap.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jmap-mcp.fullname" . }}
  labels:
    {{- include "jmap-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  session-url: {{ .Values.jmap.sessionURL | b64enc | quote }}
  auth-token: {{ .Values.jmap.authToken | b64enc | quote }}
{{- end }}
